project:
  type: website

website:
  title: "🌓 QS ☀"
  site-url: "https://thaza-kun.github.io/"
  description: "Blog peribadi Thaza"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/Thaza-Kun
      - icon: twitter
        href: https://twitter.com/Thaza_Kun
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: overlay
format:
  html:
    theme: litera
    css: styles.css
