---
draft: true
title: "Menyetidaknyahcasdiversifikasielektrostatikkan"
subtitle: "Dari mana datangnya perkataan ini?"
summary: >-
  Perkataan ini dikatakan perkataan terpanjang tapi aku meragui dakwaan tersebut.
date: "2022-02-25"
categories: [""]
images: ["/images/DNA_1920_1080.jpg"]
authors: ["Murthadza Aznam"]
---

> Perkataan "menyetidaknyahcasdiversifikasielektrostatikkan" adalah istilah sains yang terpanjang dalam bahasa Melayu.
> Nama tersebut mengandungi empat puluh enam (46) huruf.

Begitulah trivia yang aku baca dikongsi oleh peminat bahasa.
Malah,
Sebagai orang yang berkecimpung dalam bidang sains, aku hairan kerana aku sendiri tak pernah dengar istilah ini:
tidak kiralah dalam bahasa Inggeris atau bahasa Melayu.

Jadi, aku cuba gali asal-usul istilah ini.

## Istilah Asing?

Terkaan pertama aku, ialah ia adalah satu istilah asing yang diterjemahkan (dan aku syak ramai orang lain juga berfikiran begini).
Memang begitulah tanggapan kita terhadap perkataan yang pelik-pelik.
Tidak hairanlah ia selalu dipetik bersama 'istilah' bahasa Inggerisnya, "_to undiversify uncharged electrostatic electricity_" tanpa apa-apa keterangan tentang maksudnya.

Yang hairannya, perkataan itu tak wujud pun.
Tak pernah nampak pun perkataan bahasa Inggeris tersebut digunakan dalam konteks biasa mahupun saintifik.
Carian di Google pun tidak membuahkan hasil.
Pelik bin ajaib.

## Berpaling ke Wikikamus

Aku perasan, tulisan-tulisan yang menyatakan trivia 'menyetidaknyahcasdiversifikasielektrostatikkan' ini akan merujuk ke wikikamus.
Di wikikamus, aku dapat petunjuk pertama.

...lihat sejarah suntingannya...
